Repository boymilo/TeamACodeChallenge7, pull requests merged in 2021-02, with the labels that each got.

#8 [lukas] Menambahkan activity about
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamacodechallenge7/ui/about/AboutActivity.kt
  app/src/main/res/drawable/ic_logo_gubake.xml
  app/src/main/res/layout/activity_about.xml
Labels: additions

#9 Feature/login
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamacodechallenge7/data/local/SharedPref.kt
  app/src/main/java/com/teamacodechallenge7/data/model/LoginMsg.kt
  app/src/main/java/com/teamacodechallenge7/data/model/LoginRequest.kt
  app/src/main/java/com/teamacodechallenge7/data/remote/ApiModule.kt
  app/src/main/java/com/teamacodechallenge7/data/remote/ApiService.kt
  app/src/main/java/com/teamacodechallenge7/data/repository/LoginFactory.kt
  app/src/main/java/com/teamacodechallenge7/ui/loginPage/LoginAct.kt
  app/src/main/java/com/teamacodechallenge7/ui/loginPage/LoginViewModel.kt
  app/src/main/java/com/teamacodechallenge7/ui/mainMenu/MainMenuAct.kt
  app/src/main/java/com/teamacodechallenge7/ui/profileteman/ProfileTemanViewModel.kt
  app/src/main/res/drawable/ic_logo_gubake.xml
  app/src/main/res/layout/activity_about.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main_menu.xml
  app/src/main/res/layout/activity_profile_teman.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
Labels: Improvement, additions, bug

#12 [lukas] Menambahkan activity dan ui sign up
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamacodechallenge7/data/model/SignUpMsg.kt
  app/src/main/java/com/teamacodechallenge7/data/model/SignUpRequest.kt
  app/src/main/java/com/teamacodechallenge7/data/remote/ApiService.kt
  app/src/main/java/com/teamacodechallenge7/ui/signUp/SignUpActivity.kt
  app/src/main/java/com/teamacodechallenge7/ui/signUp/SignUpViewModel.kt
  app/src/main/res/drawable/ic_back_white.xml
  app/src/main/res/layout/activity_sign_up.xml
Labels: additions

#14 Feature/login
  app/src/main/java/com/teamacodechallenge7/ui/loginPage/LoginViewModel.kt
  app/src/main/java/com/teamacodechallenge7/utils/errorHandling.kt
Labels: Improvement

#16 Feature/skor
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamacodechallenge7/data/local/SharedPref.kt
  app/src/main/java/com/teamacodechallenge7/data/model/Users.kt
  app/src/main/java/com/teamacodechallenge7/data/remote/ApiService.kt
  app/src/main/java/com/teamacodechallenge7/ui/mainMenu/MainMenuViewModel.kt
  app/src/main/java/com/teamacodechallenge7/ui/profileplayer/EditProfilePlayer.kt
  app/src/main/java/com/teamacodechallenge7/ui/profileplayer/EditProfilePlayerViewModel.kt
  app/src/main/java/com/teamacodechallenge7/ui/profileplayer/ProfilePlayer.kt
  app/src/main/java/com/teamacodechallenge7/ui/profileteman/ProfileTeman.kt
  app/src/main/res/drawable/ic_but_plus.png
  app/src/main/res/drawable/ic_edit.png
  app/src/main/res/layout/activity_edit_profile_player.xml
  app/src/main/res/layout/activity_profile_teman.xml
  app/src/main/res/layout/addfriend_dialog.xml
Labels: Improvement, bug

#17 [lukas] Menambahkan animasi lottie setelah berhasil sign up
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamacodechallenge7/ui/signUp/NotifSignUpActivity.kt
  app/src/main/res/layout/activity_notif_sign_up.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/raw/ic_success.json
Labels: Improvement, additions

#18 Feature/mainmenu
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamacodechallenge7/data/model/Users.kt
  app/src/main/java/com/teamacodechallenge7/data/repository/MainMenuFactory.kt
  app/src/main/java/com/teamacodechallenge7/ui/loginPage/LoginAct.kt
  app/src/main/java/com/teamacodechallenge7/ui/loginPage/LoginViewModel.kt
  app/src/main/java/com/teamacodechallenge7/ui/mainMenu/ChooseGamePlayAct.kt
  app/src/main/java/com/teamacodechallenge7/ui/mainMenu/MainMenuAct.kt
  app/src/main/java/com/teamacodechallenge7/ui/mainMenu/MainMenuViewModel.kt
  app/src/main/java/com/teamacodechallenge7/utils/errorHandling.kt
  app/src/main/res/drawable/bg_box_blue_round.xml
  app/src/main/res/drawable/ic_bt_play_computer.xml
  app/src/main/res/drawable/ic_bt_play_other.xml
  app/src/main/res/layout/activity_choose_game_play.xml
  app/src/main/res/layout/activity_main_menu.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: Improvement, additions, bug

#19 Feature/skor
  .idea/jarRepositories.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamacodechallenge7/data/remote/ApiService.kt
  app/src/main/java/com/teamacodechallenge7/ui/profileplayer/EditProfilePlayer.kt
  app/src/main/java/com/teamacodechallenge7/ui/profileplayer/EditProfilePlayerViewModel.kt
  app/src/main/java/com/teamacodechallenge7/ui/profileplayer/ProfilePlayer.kt
  app/src/main/java/com/teamacodechallenge7/ui/profileplayer/ProfilePlayerViewModel.kt
  app/src/main/java/com/teamacodechallenge7/ui/skor/Skor.kt
  app/src/main/java/com/teamacodechallenge7/ui/skor/SkorViewModel.kt
  app/src/main/res/layout/activity_edit_profile_player.xml
  app/src/main/res/layout/activity_profile_player.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: additions, bug

#27 Bug/login
  app/src/main/java/com/teamacodechallenge7/ui/loginPage/LoginViewModel.kt
  app/src/main/java/com/teamacodechallenge7/ui/mainMenu/MainMenuViewModel.kt
  app/src/main/java/com/teamacodechallenge7/utils/refreshToken.kt
  app/src/main/res/layout/activity_main_menu.xml
Labels: bug

#35 Feature/UI
  app/src/main/java/com/teamacodechallenge7/ui/about/AboutActivity.kt
  app/src/main/java/com/teamacodechallenge7/ui/mainMenu/ChooseGamePlayAct.kt
  app/src/main/java/com/teamacodechallenge7/ui/mainMenu/MainMenuAct.kt
  app/src/main/java/com/teamacodechallenge7/ui/mainMenu/MainMenuViewModel.kt
  app/src/main/java/com/teamacodechallenge7/ui/profileplayer/ProfilePlayer.kt
  app/src/main/java/com/teamacodechallenge7/ui/signUp/SignUpActivity.kt
  app/src/main/java/com/teamacodechallenge7/ui/splashScreen/SplashScreenActivity.kt
  app/src/main/res/anim/anim_splash_screen.xml
  app/src/main/res/drawable/bg_box_orange_dark_round.xml
  app/src/main/res/drawable/bg_outer_profile.xml
  app/src/main/res/drawable/butt_orange.xml
  app/src/main/res/layout/activity_about.xml
  app/src/main/res/layout/activity_choose_game_play.xml
  app/src/main/res/layout/activity_instruction.xml
  app/src/main/res/layout/activity_landing_page.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main_menu.xml
  app/src/main/res/layout/activity_notif_sign_up.xml
  app/src/main/res/layout/activity_profile_player.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/activity_splash_screen.xml
  app/src/main/res/layout/addfriend_dialog.xml
  app/src/main/res/layout/fragment_second.xml
  app/src/main/res/layout/item_skor.xml
  app/src/main/res/layout/item_teman.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: Improvement, additions

#39 [lukas] Memperbaiki ui, code, dan logic signup
  app/src/main/java/com/teamacodechallenge7/data/model/SignUpMsg.kt
  app/src/main/java/com/teamacodechallenge7/data/model/SignUpRequest.kt
  app/src/main/java/com/teamacodechallenge7/data/remote/ApiService.kt
  app/src/main/java/com/teamacodechallenge7/ui/signUp/SignUpActivity.kt
  app/src/main/java/com/teamacodechallenge7/ui/signUp/SignUpViewModel.kt
  app/src/main/res/layout/activity_sign_up.xml
Labels: Improvement, bug

#44 Feature/UI
  app/src/main/java/com/teamacodechallenge7/ui/mainMenu/MainMenuAct.kt
  app/src/main/java/com/teamacodechallenge7/ui/profileplayer/ProfilePlayer.kt
  app/src/main/res/drawable/bg_box_white_4round.xml
  app/src/main/res/drawable/bg_but_gray1.xml
  app/src/main/res/drawable/bg_but_orange1.xml
  app/src/main/res/drawable/bg_but_red.xml
  app/src/main/res/drawable/bg_outer_profile_menu.xml
  app/src/main/res/layout/activity_main_menu.xml
  app/src/main/res/layout/activity_profile_player.xml
  app/src/main/res/raw/ic_about.json
  app/src/main/res/raw/ic_info.json
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: additions

#45 Feature/UI
  app/src/main/java/com/teamacodechallenge7/ui/about/AboutActivity.kt
  app/src/main/java/com/teamacodechallenge7/ui/mainMenu/ChooseGamePlayAct.kt
  app/src/main/java/com/teamacodechallenge7/ui/mainMenu/MainMenuAct.kt
  app/src/main/java/com/teamacodechallenge7/ui/profileplayer/EditProfilePlayer.kt
  app/src/main/res/drawable/bg_et_blue.xml
  app/src/main/res/drawable/bg_et_profile.xml
  app/src/main/res/drawable/bg_orange_dark.xml
  app/src/main/res/drawable/bg_shape1.xml
  app/src/main/res/drawable/ic_close_white.xml
  app/src/main/res/layout/activity_about.xml
  app/src/main/res/layout/activity_choose_game_play.xml
  app/src/main/res/layout/activity_edit_profile_player.xml
  app/src/main/res/layout/activity_main_menu.xml
  app/src/main/res/layout/activity_pilih_lawan.xml
  app/src/main/res/layout/activity_play_game_vs_computer.xml
  app/src/main/res/layout/activity_profile_teman.xml
  app/src/main/res/layout/addfriend_dialog.xml
  app/src/main/res/values/strings.xml
Labels: additions

#46 [lukas] Memperbaiki gameplay
  app/src/main/java/com/teamacodechallenge7/ui/playgamevsplayer/PlayGameVsPlayer.kt
  app/src/main/res/layout/activity_play_game_vs_player.xml
Labels: Improvement

#55 [lukas] Mengganti logic game player vs player
  app/src/main/java/com/teamacodechallenge7/ui/playgamevsplayer/PlayGameVsPlayer.kt
  app/src/main/res/layout/activity_play_game_vs_player.xml
Labels: additions

#57 fix bug
  app/src/main/java/com/teamacodechallenge7/ui/playgamevscomputer/PlayGameVsComputer.kt
  app/src/main/res/layout/activity_play_game_vs_computer.xml
Labels: bug

#58 Bug/apps
  app/src/main/java/com/teamacodechallenge7/ui/gamehistory/GameHistoryAct.kt
  app/src/main/java/com/teamacodechallenge7/ui/gamehistory/GameHistoryAdapter.kt
  app/src/main/java/com/teamacodechallenge7/ui/playgamevsplayer/PlayGameVsPlayer.kt
  app/src/main/java/com/teamacodechallenge7/ui/profileplayer/EditProfilePlayer.kt
  app/src/main/java/com/teamacodechallenge7/utils/getDate.kt
  app/src/main/java/com/teamacodechallenge7/utils/refreshToken.kt
  app/src/main/res/layout/activity_about.xml
  app/src/main/res/layout/activity_choose_game_play.xml
  app/src/main/res/layout/activity_edit_profile_player.xml
  app/src/main/res/layout/activity_game_history.xml
  app/src/main/res/layout/activity_instruction.xml
  app/src/main/res/layout/activity_landing_page.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main_menu.xml
  app/src/main/res/layout/activity_notif_sign_up.xml
  app/src/main/res/layout/activity_pilih_lawan.xml
  app/src/main/res/layout/activity_play_game_vs_computer.xml
  app/src/main/res/layout/activity_play_game_vs_player.xml
  app/src/main/res/layout/activity_profile_player.xml
  app/src/main/res/layout/activity_profile_teman.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/addfriend_dialog.xml
  app/src/main/res/layout/item_skor.xml
  app/src/main/res/values/strings.xml
Labels: Improvement, additions, bug

#59 Bug/apps
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamacodechallenge7/ui/gamehistory/GameHistoryAct.kt
  app/src/main/java/com/teamacodechallenge7/ui/loginPage/LoginAct.kt
  app/src/main/java/com/teamacodechallenge7/ui/loginPage/LoginViewModel.kt
  app/src/main/java/com/teamacodechallenge7/ui/mainMenu/ChooseGamePlayAct.kt
  app/src/main/java/com/teamacodechallenge7/ui/mainMenu/MainMenuAct.kt
  app/src/main/java/com/teamacodechallenge7/ui/pilihlawan/PilihLawan.kt
  app/src/main/java/com/teamacodechallenge7/ui/pilihlawan/PilihLawanAdapter.kt
  app/src/main/java/com/teamacodechallenge7/ui/playgamevscomputer/PlayGameVsComputer.kt
  app/src/main/java/com/teamacodechallenge7/ui/playgamevsplayer/PlayGameVsPlayer.kt
  app/src/main/java/com/teamacodechallenge7/ui/profileplayer/EditProfilePlayer.kt
  app/src/main/java/com/teamacodechallenge7/ui/profileplayer/EditProfilePlayerViewModel.kt
  app/src/main/java/com/teamacodechallenge7/ui/profileplayer/ProfilePlayer.kt
  app/src/main/java/com/teamacodechallenge7/ui/profileteman/ProfileTeman.kt
  app/src/main/java/com/teamacodechallenge7/ui/signUp/SignUpActivity.kt
  app/src/main/java/com/teamacodechallenge7/ui/signUp/SignUpViewModel.kt
  app/src/main/java/com/teamacodechallenge7/utils/GameMusic.kt
  app/src/main/java/com/teamacodechallenge7/utils/GamePlayMusic.kt
  app/src/main/res/drawable/ic_bt_play_computer.xml
  app/src/main/res/drawable/ic_bt_play_other.xml
  app/src/main/res/drawable/ic_logo_dark.xml
  app/src/main/res/drawable/ic_user.xml
  app/src/main/res/layout/activity_about.xml
  app/src/main/res/layout/activity_edit_profile_player.xml
  app/src/main/res/layout/activity_landing_page.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main_menu.xml
  app/src/main/res/layout/activity_pilih_lawan.xml
  app/src/main/res/layout/activity_play_game_vs_computer.xml
  app/src/main/res/layout/activity_play_game_vs_player.xml
  app/src/main/res/layout/activity_profile_player.xml
  app/src/main/res/layout/activity_profile_teman.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/addfriend_dialog.xml
  app/src/main/res/layout/item_teman.xml
  build.gradle
Labels: Improvement, additions, bug

#60 [lukas] Memperbaiki bug pada password dan username
  app/src/main/java/com/teamacodechallenge7/ui/signUp/SignUpViewModel.kt
Labels: bug

#63 Feature/UI
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/res/layout/activity_about.xml
  app/src/main/res/layout/activity_edit_profile_player.xml
  app/src/main/res/layout/activity_landing_page.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main_menu.xml
  app/src/main/res/layout/activity_play_game_vs_computer.xml
  app/src/main/res/layout/activity_play_game_vs_player.xml
  app/src/main/res/layout/activity_profile_player.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/addfriend_dialog.xml
  app/src/main/res/layout/item_teman.xml
Labels: bug
