Repository boymilo/TeamACodeChallenge7, pull requests merged in 2021-01, with the labels that each got.

#1 update gradle & package
  .idea/vcs.xml
  app/build.gradle
  app/src/main/java/com/teamacodechallenge7/data/database/Teman.kt
  app/src/main/java/com/teamacodechallenge7/data/database/TemanDao.kt
  app/src/main/java/com/teamacodechallenge7/data/database/TemanDatabase.kt
  app/src/main/java/com/teamacodechallenge7/data/remote/ApiModule.kt
  app/src/main/java/com/teamacodechallenge7/data/remote/ApiService.kt
Labels: additions

#4 Feature/skor
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamacodechallenge7/ui/profileteman/ProfileTeman.kt
  app/src/main/java/com/teamacodechallenge7/ui/profileteman/ProfileTemanViewModel.kt
  app/src/main/res/drawable/background.xml
  app/src/main/res/drawable/background_dialog.xml
  app/src/main/res/drawable/bg_button.xml
  app/src/main/res/drawable/bg_shape.xml
  app/src/main/res/drawable/butt_green.xml
  app/src/main/res/drawable/butt_orange.xml
  app/src/main/res/drawable/ic_battle_image.xml
  app/src/main/res/drawable/ic_batu_but.xml
  app/src/main/res/drawable/ic_close_but.xml
  app/src/main/res/drawable/ic_delete.xml
  app/src/main/res/drawable/ic_edit.xml
  app/src/main/res/drawable/ic_home.xml
  app/src/main/res/drawable/ic_landing_page1.xml
  app/src/main/res/drawable/ic_landing_page2.xml
  app/src/main/res/drawable/ic_logo_image.xml
  app/src/main/res/drawable/ic_paper_but.xml
  app/src/main/res/drawable/ic_people.xml
  app/src/main/res/drawable/ic_scissors_but.xml
  app/src/main/res/layout/activity_profile_teman.xml
  app/src/main/res/layout/addfriend_dialog.xml
Labels: additions

#5 hapus drawable,update design login, update color dan ui login
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/ic_logo_apps-playstore.png
  app/src/main/java/com/teamacodechallenge7/ui/loginPage/LoginAct.kt
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/bg_box_white_round.xml
  app/src/main/res/drawable/bg_but_gray.xml
  app/src/main/res/drawable/bg_but_orange.xml
  app/src/main/res/drawable/bg_et_gray.xml
  app/src/main/res/drawable/bg_et_green.xml
  app/src/main/res/drawable/bg_et_signinup.xml
  app/src/main/res/drawable/bg_signin_signup.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_logo_dark.xml
  app/src/main/res/drawable/ic_logo_white.xml
  app/src/main/res/layout/activity_landing_page.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/mipmap-anydpi-v26/ic_logo_apps.xml
  app/src/main/res/mipmap-anydpi-v26/ic_logo_apps_round.xml
  app/src/main/res/mipmap-hdpi/ic_logo_apps.png
  app/src/main/res/mipmap-hdpi/ic_logo_apps_foreground.png
  app/src/main/res/mipmap-hdpi/ic_logo_apps_round.png
  app/src/main/res/mipmap-mdpi/ic_logo_apps.png
  app/src/main/res/mipmap-mdpi/ic_logo_apps_foreground.png
  app/src/main/res/mipmap-mdpi/ic_logo_apps_round.png
  app/src/main/res/mipmap-xhdpi/ic_logo_apps.png
  app/src/main/res/mipmap-xhdpi/ic_logo_apps_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_logo_apps_round.png
  app/src/main/res/mipmap-xxhdpi/ic_logo_apps.png
  app/src/main/res/mipmap-xxhdpi/ic_logo_apps_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_logo_apps_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_logo_apps.png
  app/src/main/res/mipmap-xxxhdpi/ic_logo_apps_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_logo_apps_round.png
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/ic_logo_apps_background.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: Improvement, additions

#6 benarin ui nya profile teman, addfriend, fragment, login
  README.md
  app/src/main/res/drawable/background_dialog.xml
  app/src/main/res/drawable/bg_button.xml
  app/src/main/res/drawable/bg_green.xml
  app/src/main/res/drawable/bg_shape.xml
  app/src/main/res/drawable/bg_white.xml
  app/src/main/res/drawable/butt_green.xml
  app/src/main/res/drawable/butt_orange.xml
  app/src/main/res/drawable/ic_back_blue.xml
  app/src/main/res/drawable/ic_battle_image.xml
  app/src/main/res/drawable/ic_batu_but.xml
  app/src/main/res/drawable/ic_close.xml
  app/src/main/res/drawable/ic_close_but.xml
  app/src/main/res/drawable/ic_delete.xml
  app/src/main/res/drawable/ic_edit.xml
  app/src/main/res/drawable/ic_home.xml
  app/src/main/res/drawable/ic_landing_page1.xml
  app/src/main/res/drawable/ic_landing_page2.xml
  app/src/main/res/drawable/ic_landing_page_1.xml
  app/src/main/res/drawable/ic_landing_page_2.xml
  app/src/main/res/drawable/ic_logo_image.xml
  app/src/main/res/drawable/ic_logo_white.xml
  app/src/main/res/drawable/ic_paper_but.xml
  app/src/main/res/drawable/ic_people.xml
  app/src/main/res/drawable/ic_scissors_but.xml
  app/src/main/res/layout/activity_landing_page.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_profile_teman.xml
  app/src/main/res/layout/activity_splash_screen.xml
  app/src/main/res/layout/addfriend_dialog.xml
  app/src/main/res/layout/fragment_second.xml
  app/src/main/res/values/colors.xml
Labels: bug
